# Server configuration ...
port = ":8080"
log_level = "debug"

# Page configuration ...
static = "web/static"
templates = "web/"

# Database configuration ...
sql_url = "user=postgres password=12345 dbname=web port=5432 sslmode=disable"

# JWT
token_password = "supersecretpass"